/**
 * bun run vercel:env -- --web-url https://<project>.vercel.app [--public-rpc <url>] [--with-admin-key]
 *
 * Writes `.env.vercel` (git-ignored, mode 600) with every variable the web app
 * needs on Vercel (docs/DEPLOY.md), ready to paste into Project → Settings →
 * Environment Variables ("paste .env"). Prints variable NAMES only, never values.
 *
 * Sources: DEVNET_RPC_URL (server RPC, secret), VERCEL_DATABASE_URL or else
 * DEVNET_DATABASE_URL (Neon; the pooled "-pooler" URL is best for Vercel),
 * .keys/admin.json only with --with-admin-key (enables the devnet SOL faucet, D038).
 */
import { chmodSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { wsFromRpc } from "@repo/sdk";
import { argValue } from "./lib/chain";
import { log } from "./lib/proc";
import { ROOT } from "./lib/toolchain";

const S = "vercel-env";
const webUrl = (argValue("web-url") || process.env.DEVNET_WEB_URL || "").replace(/\/+$/, "");
const serverRpc = process.env.DEVNET_RPC_URL || "https://api.devnet.solana.com";
const publicRpc = argValue("public-rpc") || "https://api.devnet.solana.com";
const dbUrl = process.env.VERCEL_DATABASE_URL || process.env.DEVNET_DATABASE_URL || "";
const withAdmin = process.argv.includes("--with-admin-key");

const problems: string[] = [];
if (!webUrl.startsWith("https://"))
  problems.push("--web-url https://<project>.vercel.app is required");
if (!dbUrl)
  problems.push("set VERCEL_DATABASE_URL (Neon pooled URL) or DEVNET_DATABASE_URL in .env");
if (dbUrl && /localhost|127\.0\.0\.1/.test(dbUrl))
  problems.push("the database URL points to localhost");
if (problems.length) {
  for (const p of problems) console.error(`[${S}] ${p}`);
  process.exit(1);
}

const vars: [string, string][] = [
  ["CLUSTER", "devnet"],
  ["NEXT_PUBLIC_CLUSTER", "devnet"],
  ["RPC_URL", serverRpc],
  ["WS_URL", wsFromRpc(serverRpc)],
  ["NEXT_PUBLIC_RPC_URL", publicRpc],
  ["NEXT_PUBLIC_WS_URL", wsFromRpc(publicRpc)],
  ["NEXT_PUBLIC_APP_NAME", process.env.NEXT_PUBLIC_APP_NAME || "Stockbreak"],
  ["WEB_URL", webUrl],
  ["DATABASE_URL", dbUrl],
  ["FAUCET_SOL_PER_REQUEST", "0.1"],
  ["FAUCET_SOL_DAILY_CAP", "1"],
];
if (withAdmin) {
  const p = path.join(ROOT, process.env.ADMIN_KEYPAIR_PATH || ".keys/admin.json");
  if (!existsSync(p)) {
    console.error(`[${S}] admin keypair not found`);
    process.exit(1);
  }
  vars.push(["ADMIN_KEYPAIR_JSON", JSON.stringify(JSON.parse(readFileSync(p, "utf8")))]);
}

const out = path.join(ROOT, ".env.vercel");
writeFileSync(
  out,
  `# Generated by bun run vercel:env — secrets inside, never commit (git-ignored).\n${vars
    .map(([k, v]) => `${k}=${v}`)
    .join("\n")}\n`,
  { mode: 0o600 },
);
chmodSync(out, 0o600); // an existing file keeps its old mode on write
log(S, `wrote .env.vercel with: ${vars.map(([k]) => k).join(", ")}`);
if (publicRpc === serverRpc)
  log(
    S,
    "note: NEXT_PUBLIC_RPC_URL equals the server RPC; its API key is visible to every visitor",
  );
if (!withAdmin)
  log(S, "SOL faucet will be off (no ADMIN_KEYPAIR_JSON); users get SOL at faucet.solana.com");
